<!DOCTYPE html>
<html lang="en">
<head>
    <meta content="Archery Club University of Waterloo Bow Arrow UW Campus Recreation Fita OAA Ontario Association of Archers Archer Shooting Coaching Lessons"
          name="keywords" />
    <meta content="The University of Waterloo Archery Club is an Athletic Club available to University of Waterloo Students under the Campus Recreation Program. The club provides a fun and relaxed atmosphere for the promotion and enjoyment of archery. The club has a selection of equipment and coaches available for beginner and intermediate archers."
          name="description" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>University of Waterloo Archery Club</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link href="/static/css/style.css" type="text/css" rel="stylesheet" />
</head>

<body>
<div class="bg">&nbsp;</div>
<div id="content">
    <div id="scroller">
        <div id="logo"><img alt="logo" src="/static/img/logo.png" /></div>

        <div id="menu">
            <a href="index.php">
                Home
            </a>
            <a href="events.php">
                Events
            </a>
            <a href="equip.php">
                Equipment
            </a>
            <a href="exec.php">
                Committee
            </a>
            <a href="faq.php">
                FAQ
            </a>

            <a href="https://www.facebook.com/groups/uwaterlooarchery/">
                <img src="//i.imgur.com/Z3uwi.gif" />
            </a>
        </div>

        <div id="content2">
            {{ content }}
        </div>

        <footer class="center">&copy; | <a href="exec.php">contact us</a></footer>
    </div>
</div>
<!-- Start of StatCounter Code -->
  <script type="text/javascript">//<![CDATA[
  var sc_project=4446854;var sc_invisible=1;var sc_partition=55;var sc_click_stat=1;var sc_security="74785e80";
  //]]></script><script type="text/javascript" src="http://www.statcounter.com/counter/counter_xhtml.js">
</script><a href="http://ohai.ca" style="display:none;">ohai</a> 
<!-- End of StatCounter Code -->
</body>
</html>